2024-02-19 23:55:45,407:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2024-02-19 23:55:45,407:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2024-02-19 23:55:45,407:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2024-02-19 23:55:45,407:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2024-02-19 23:57:01,656:INFO:PyCaret ClassificationExperiment
2024-02-19 23:57:01,656:INFO:Logging name: clf-default-name
2024-02-19 23:57:01,656:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2024-02-19 23:57:01,656:INFO:version 3.2.0
2024-02-19 23:57:01,657:INFO:Initializing setup()
2024-02-19 23:57:01,657:INFO:self.USI: cc2a
2024-02-19 23:57:01,657:INFO:self._variable_keys: {'exp_id', 'log_plots_param', '_ml_usecase', 'gpu_n_jobs_param', 'gpu_param', 'html_param', 'X', 'seed', '_available_plots', 'y_test', 'fold_groups_param', 'y_train', 'is_multiclass', 'logging_param', 'X_train', 'fold_generator', 'USI', 'memory', 'X_test', 'y', 'fold_shuffle_param', 'target_param', 'exp_name_log', 'data', 'n_jobs_param', 'pipeline', 'idx', 'fix_imbalance'}
2024-02-19 23:57:01,657:INFO:Checking environment
2024-02-19 23:57:01,657:INFO:python_version: 3.11.2
2024-02-19 23:57:01,657:INFO:python_build: ('main', 'Mar 13 2023 12:18:29')
2024-02-19 23:57:01,657:INFO:machine: x86_64
2024-02-19 23:57:01,658:INFO:platform: Linux-6.5.0-13parrot1-amd64-x86_64-with-glibc2.36
2024-02-19 23:57:01,658:INFO:Memory: svmem(total=8111816704, available=1170661376, percent=85.6, used=6387957760, free=376643584, active=5247647744, inactive=1885061120, buffers=8192, cached=1347207168, shared=279269376, slab=246464512)
2024-02-19 23:57:01,659:INFO:Physical Core: 2
2024-02-19 23:57:01,659:INFO:Logical Core: 4
2024-02-19 23:57:01,660:INFO:Checking libraries
2024-02-19 23:57:01,660:INFO:System:
2024-02-19 23:57:01,660:INFO:    python: 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
2024-02-19 23:57:01,660:INFO:executable: /home/sensei/Repos/EDA-Analysis/EDA_venv/bin/python3
2024-02-19 23:57:01,662:INFO:   machine: Linux-6.5.0-13parrot1-amd64-x86_64-with-glibc2.36
2024-02-19 23:57:01,662:INFO:PyCaret required dependencies:
2024-02-19 23:57:06,405:INFO:                 pip: 23.0.1
2024-02-19 23:57:06,405:INFO:          setuptools: 66.1.1
2024-02-19 23:57:06,405:INFO:             pycaret: 3.2.0
2024-02-19 23:57:06,405:INFO:             IPython: 8.21.0
2024-02-19 23:57:06,405:INFO:          ipywidgets: 8.1.2
2024-02-19 23:57:06,405:INFO:                tqdm: 4.66.2
2024-02-19 23:57:06,405:INFO:               numpy: 1.25.2
2024-02-19 23:57:06,405:INFO:              pandas: 2.2.0
2024-02-19 23:57:06,406:INFO:              jinja2: 3.1.3
2024-02-19 23:57:06,406:INFO:               scipy: 1.10.1
2024-02-19 23:57:06,406:INFO:              joblib: 1.3.2
2024-02-19 23:57:06,406:INFO:             sklearn: 1.2.2
2024-02-19 23:57:06,406:INFO:                pyod: 1.1.3
2024-02-19 23:57:06,406:INFO:            imblearn: 0.12.0
2024-02-19 23:57:06,406:INFO:   category_encoders: 2.6.3
2024-02-19 23:57:06,406:INFO:            lightgbm: 4.3.0
2024-02-19 23:57:06,407:INFO:               numba: 0.59.0
2024-02-19 23:57:06,407:INFO:            requests: 2.31.0
2024-02-19 23:57:06,407:INFO:          matplotlib: 3.6.0
2024-02-19 23:57:06,407:INFO:          scikitplot: 0.3.7
2024-02-19 23:57:06,407:INFO:         yellowbrick: 1.5
2024-02-19 23:57:06,407:INFO:              plotly: 5.19.0
2024-02-19 23:57:06,407:INFO:    plotly-resampler: Not installed
2024-02-19 23:57:06,407:INFO:             kaleido: 0.2.1
2024-02-19 23:57:06,407:INFO:           schemdraw: 0.15
2024-02-19 23:57:06,407:INFO:         statsmodels: 0.14.1
2024-02-19 23:57:06,407:INFO:              sktime: 0.21.1
2024-02-19 23:57:06,407:INFO:               tbats: 1.1.3
2024-02-19 23:57:06,407:INFO:            pmdarima: 2.0.4
2024-02-19 23:57:06,407:INFO:              psutil: 5.9.8
2024-02-19 23:57:06,408:INFO:          markupsafe: 2.1.5
2024-02-19 23:57:06,408:INFO:             pickle5: Not installed
2024-02-19 23:57:06,408:INFO:         cloudpickle: 3.0.0
2024-02-19 23:57:06,408:INFO:         deprecation: 2.1.0
2024-02-19 23:57:06,408:INFO:              xxhash: 3.4.1
2024-02-19 23:57:06,408:INFO:           wurlitzer: 3.0.3
2024-02-19 23:57:06,408:INFO:PyCaret optional dependencies:
2024-02-19 23:57:06,433:INFO:                shap: Not installed
2024-02-19 23:57:06,433:INFO:           interpret: Not installed
2024-02-19 23:57:06,433:INFO:                umap: Not installed
2024-02-19 23:57:06,433:INFO:     ydata_profiling: Not installed
2024-02-19 23:57:06,433:INFO:  explainerdashboard: Not installed
2024-02-19 23:57:06,433:INFO:             autoviz: Not installed
2024-02-19 23:57:06,433:INFO:           fairlearn: Not installed
2024-02-19 23:57:06,433:INFO:          deepchecks: Not installed
2024-02-19 23:57:06,433:INFO:             xgboost: Not installed
2024-02-19 23:57:06,433:INFO:            catboost: Not installed
2024-02-19 23:57:06,433:INFO:              kmodes: Not installed
2024-02-19 23:57:06,433:INFO:             mlxtend: Not installed
2024-02-19 23:57:06,433:INFO:       statsforecast: Not installed
2024-02-19 23:57:06,434:INFO:        tune_sklearn: Not installed
2024-02-19 23:57:06,434:INFO:                 ray: Not installed
2024-02-19 23:57:06,434:INFO:            hyperopt: Not installed
2024-02-19 23:57:06,434:INFO:              optuna: Not installed
2024-02-19 23:57:06,434:INFO:               skopt: Not installed
2024-02-19 23:57:06,434:INFO:              mlflow: Not installed
2024-02-19 23:57:06,434:INFO:              gradio: Not installed
2024-02-19 23:57:06,434:INFO:             fastapi: Not installed
2024-02-19 23:57:06,434:INFO:             uvicorn: Not installed
2024-02-19 23:57:06,434:INFO:              m2cgen: Not installed
2024-02-19 23:57:06,434:INFO:           evidently: Not installed
2024-02-19 23:57:06,434:INFO:               fugue: Not installed
2024-02-19 23:57:06,434:INFO:           streamlit: Not installed
2024-02-19 23:57:06,434:INFO:             prophet: Not installed
2024-02-19 23:57:06,434:INFO:None
2024-02-19 23:57:06,434:INFO:Set up data.
2024-02-19 23:57:06,446:INFO:Set up folding strategy.
2024-02-19 23:57:06,447:INFO:Set up train/test split.
2024-02-19 23:57:06,535:INFO:Set up index.
2024-02-19 23:57:06,562:INFO:Assigning column types.
2024-02-19 23:57:06,585:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2024-02-19 23:57:06,724:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2024-02-19 23:57:06,779:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2024-02-19 23:57:06,968:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-19 23:57:06,969:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-19 23:57:07,108:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2024-02-19 23:57:07,110:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2024-02-19 23:57:07,176:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-19 23:57:07,177:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-19 23:57:07,177:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2024-02-19 23:57:07,287:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2024-02-19 23:57:07,353:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-19 23:57:07,354:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-19 23:57:07,464:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2024-02-19 23:57:07,534:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-19 23:57:07,535:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-19 23:57:07,535:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2024-02-19 23:57:07,722:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-19 23:57:07,723:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-19 23:57:07,960:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-19 23:57:07,961:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-19 23:57:09,644:INFO:Preparing preprocessing pipeline...
2024-02-19 23:57:09,648:INFO:Set up simple imputation.
2024-02-19 23:57:09,650:INFO:Set up column name cleaning.
2024-02-19 23:57:09,720:INFO:Finished creating preprocessing pipeline.
2024-02-19 23:57:10,261:INFO:Pipeline: Pipeline(memory=FastMemory(location=/tmp/joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['tenure', 'MonthlyCharges',
                                             'TotalCharges',
                                             'MonthlyCharges_log',
                                             'TotalCharges_Tenure_Ratio',
                                             'MonthlyCharges_to_TotalCharges_Ratio',
                                             'Bank transfer (automatic)',
                                             'Credit card (automatic)',
                                             'Electronic check', 'Mailed check',
                                             'Month-to-month', 'One...
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated'))),
                ('clean_column_names',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+')))],
         verbose=False)
2024-02-19 23:57:10,261:INFO:Creating final display dataframe.
2024-02-19 23:57:10,456:INFO:Setup _display_container:                     Description             Value
0                    Session id              7041
1                        Target             Churn
2                   Target type            Binary
3           Original data shape        (7032, 14)
4        Transformed data shape        (7032, 14)
5   Transformed train set shape        (4922, 14)
6    Transformed test set shape        (2110, 14)
7              Numeric features                13
8                    Preprocess              True
9               Imputation type            simple
10           Numeric imputation              mean
11       Categorical imputation              mode
12               Fold Generator   StratifiedKFold
13                  Fold Number                10
14                     CPU Jobs                -1
15                      Use GPU             False
16               Log Experiment             False
17              Experiment Name  clf-default-name
18                          USI              cc2a
2024-02-19 23:57:10,670:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-19 23:57:10,670:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-19 23:57:10,885:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-19 23:57:10,885:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-19 23:57:10,887:INFO:setup() successfully completed in 9.51s...............
2024-02-19 23:59:33,781:INFO:Initializing compare_models()
2024-02-19 23:59:33,781:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f263ebc4b50>, include=None, exclude=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x7f263ebc4b50>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>})
2024-02-19 23:59:33,782:INFO:Checking exceptions
2024-02-19 23:59:34,127:INFO:Preparing display monitor
2024-02-19 23:59:34,191:INFO:Initializing Logistic Regression
2024-02-19 23:59:34,191:INFO:Total runtime is 5.205472310384114e-06 minutes
2024-02-19 23:59:34,202:INFO:SubProcess create_model() called ==================================
2024-02-19 23:59:34,202:INFO:Initializing create_model()
2024-02-19 23:59:34,203:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f263ebc4b50>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f263fcaead0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-19 23:59:34,203:INFO:Checking exceptions
2024-02-19 23:59:34,203:INFO:Importing libraries
2024-02-19 23:59:34,203:INFO:Copying training dataset
2024-02-19 23:59:34,225:INFO:Defining folds
2024-02-19 23:59:34,225:INFO:Declaring metric variables
2024-02-19 23:59:34,238:INFO:Importing untrained model
2024-02-19 23:59:34,248:INFO:Logistic Regression Imported successfully
2024-02-19 23:59:34,274:INFO:Starting cross validation
2024-02-19 23:59:34,276:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-02-20 00:01:27,029:INFO:Calculating mean and std
2024-02-20 00:01:27,483:INFO:Creating metrics dataframe
2024-02-20 00:01:27,491:INFO:Uploading results into container
2024-02-20 00:01:27,493:INFO:Uploading model into container now
2024-02-20 00:01:27,495:INFO:_master_model_container: 1
2024-02-20 00:01:27,495:INFO:_display_container: 2
2024-02-20 00:01:27,496:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=7041, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2024-02-20 00:01:27,496:INFO:create_model() successfully completed......................................
2024-02-20 00:01:27,853:INFO:SubProcess create_model() end ==================================
2024-02-20 00:01:27,853:INFO:Creating metrics dataframe
2024-02-20 00:01:27,867:INFO:Initializing K Neighbors Classifier
2024-02-20 00:01:27,868:INFO:Total runtime is 1.8946149190266925 minutes
2024-02-20 00:01:27,875:INFO:SubProcess create_model() called ==================================
2024-02-20 00:01:27,876:INFO:Initializing create_model()
2024-02-20 00:01:27,876:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f263ebc4b50>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f263fcaead0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-20 00:01:27,876:INFO:Checking exceptions
2024-02-20 00:01:27,876:INFO:Importing libraries
2024-02-20 00:01:27,877:INFO:Copying training dataset
2024-02-20 00:01:27,896:INFO:Defining folds
2024-02-20 00:01:27,897:INFO:Declaring metric variables
2024-02-20 00:01:27,902:INFO:Importing untrained model
2024-02-20 00:01:27,914:INFO:K Neighbors Classifier Imported successfully
2024-02-20 00:01:27,929:INFO:Starting cross validation
2024-02-20 00:01:27,930:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-02-20 00:01:28,714:INFO:Calculating mean and std
2024-02-20 00:01:28,716:INFO:Creating metrics dataframe
2024-02-20 00:01:28,719:INFO:Uploading results into container
2024-02-20 00:01:28,720:INFO:Uploading model into container now
2024-02-20 00:01:28,722:INFO:_master_model_container: 2
2024-02-20 00:01:28,722:INFO:_display_container: 2
2024-02-20 00:01:28,723:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2024-02-20 00:01:28,726:INFO:create_model() successfully completed......................................
2024-02-20 00:01:28,913:INFO:SubProcess create_model() end ==================================
2024-02-20 00:01:28,913:INFO:Creating metrics dataframe
2024-02-20 00:01:28,926:INFO:Initializing Naive Bayes
2024-02-20 00:01:28,926:INFO:Total runtime is 1.9122541944185891 minutes
2024-02-20 00:01:28,931:INFO:SubProcess create_model() called ==================================
2024-02-20 00:01:28,931:INFO:Initializing create_model()
2024-02-20 00:01:28,932:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f263ebc4b50>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f263fcaead0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-20 00:01:28,933:INFO:Checking exceptions
2024-02-20 00:01:28,933:INFO:Importing libraries
2024-02-20 00:01:28,933:INFO:Copying training dataset
2024-02-20 00:01:28,955:INFO:Defining folds
2024-02-20 00:01:28,956:INFO:Declaring metric variables
2024-02-20 00:01:28,969:INFO:Importing untrained model
2024-02-20 00:01:28,979:INFO:Naive Bayes Imported successfully
2024-02-20 00:01:29,010:INFO:Starting cross validation
2024-02-20 00:01:29,013:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-02-20 00:01:29,728:INFO:Calculating mean and std
2024-02-20 00:01:29,730:INFO:Creating metrics dataframe
2024-02-20 00:01:29,733:INFO:Uploading results into container
2024-02-20 00:01:29,734:INFO:Uploading model into container now
2024-02-20 00:01:29,735:INFO:_master_model_container: 3
2024-02-20 00:01:29,736:INFO:_display_container: 2
2024-02-20 00:01:29,737:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2024-02-20 00:01:29,737:INFO:create_model() successfully completed......................................
2024-02-20 00:01:29,928:INFO:SubProcess create_model() end ==================================
2024-02-20 00:01:29,928:INFO:Creating metrics dataframe
2024-02-20 00:01:29,940:INFO:Initializing Decision Tree Classifier
2024-02-20 00:01:29,940:INFO:Total runtime is 1.9291626850763954 minutes
2024-02-20 00:01:29,945:INFO:SubProcess create_model() called ==================================
2024-02-20 00:01:29,946:INFO:Initializing create_model()
2024-02-20 00:01:29,946:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f263ebc4b50>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f263fcaead0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-20 00:01:29,946:INFO:Checking exceptions
2024-02-20 00:01:29,946:INFO:Importing libraries
2024-02-20 00:01:29,946:INFO:Copying training dataset
2024-02-20 00:01:29,968:INFO:Defining folds
2024-02-20 00:01:29,968:INFO:Declaring metric variables
2024-02-20 00:01:29,980:INFO:Importing untrained model
2024-02-20 00:01:29,995:INFO:Decision Tree Classifier Imported successfully
2024-02-20 00:01:30,017:INFO:Starting cross validation
2024-02-20 00:01:30,019:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-02-20 00:01:30,545:INFO:Calculating mean and std
2024-02-20 00:01:30,547:INFO:Creating metrics dataframe
2024-02-20 00:01:30,550:INFO:Uploading results into container
2024-02-20 00:01:30,551:INFO:Uploading model into container now
2024-02-20 00:01:30,552:INFO:_master_model_container: 4
2024-02-20 00:01:30,552:INFO:_display_container: 2
2024-02-20 00:01:30,553:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=7041, splitter='best')
2024-02-20 00:01:30,553:INFO:create_model() successfully completed......................................
2024-02-20 00:01:30,744:INFO:SubProcess create_model() end ==================================
2024-02-20 00:01:30,745:INFO:Creating metrics dataframe
2024-02-20 00:01:30,758:INFO:Initializing SVM - Linear Kernel
2024-02-20 00:01:30,758:INFO:Total runtime is 1.942789836724599 minutes
2024-02-20 00:01:30,763:INFO:SubProcess create_model() called ==================================
2024-02-20 00:01:30,764:INFO:Initializing create_model()
2024-02-20 00:01:30,764:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f263ebc4b50>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f263fcaead0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-20 00:01:30,764:INFO:Checking exceptions
2024-02-20 00:01:30,764:INFO:Importing libraries
2024-02-20 00:01:30,764:INFO:Copying training dataset
2024-02-20 00:01:30,787:INFO:Defining folds
2024-02-20 00:01:30,788:INFO:Declaring metric variables
2024-02-20 00:01:30,799:INFO:Importing untrained model
2024-02-20 00:01:30,809:INFO:SVM - Linear Kernel Imported successfully
2024-02-20 00:01:30,830:INFO:Starting cross validation
2024-02-20 00:01:30,831:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-02-20 00:01:31,709:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2024-02-20 00:01:31,709:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2024-02-20 00:01:31,710:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2024-02-20 00:01:31,711:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2024-02-20 00:01:31,887:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2024-02-20 00:01:31,892:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2024-02-20 00:01:31,939:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2024-02-20 00:01:31,957:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2024-02-20 00:01:32,039:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2024-02-20 00:01:32,040:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2024-02-20 00:01:32,064:INFO:Calculating mean and std
2024-02-20 00:01:32,067:INFO:Creating metrics dataframe
2024-02-20 00:01:32,071:INFO:Uploading results into container
2024-02-20 00:01:32,072:INFO:Uploading model into container now
2024-02-20 00:01:32,072:INFO:_master_model_container: 5
2024-02-20 00:01:32,072:INFO:_display_container: 2
2024-02-20 00:01:32,074:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=7041, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2024-02-20 00:01:32,074:INFO:create_model() successfully completed......................................
2024-02-20 00:01:32,254:INFO:SubProcess create_model() end ==================================
2024-02-20 00:01:32,255:INFO:Creating metrics dataframe
2024-02-20 00:01:32,267:INFO:Initializing Ridge Classifier
2024-02-20 00:01:32,268:INFO:Total runtime is 1.9679516235987344 minutes
2024-02-20 00:01:32,274:INFO:SubProcess create_model() called ==================================
2024-02-20 00:01:32,275:INFO:Initializing create_model()
2024-02-20 00:01:32,275:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f263ebc4b50>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f263fcaead0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-20 00:01:32,275:INFO:Checking exceptions
2024-02-20 00:01:32,275:INFO:Importing libraries
2024-02-20 00:01:32,275:INFO:Copying training dataset
2024-02-20 00:01:32,291:INFO:Defining folds
2024-02-20 00:01:32,291:INFO:Declaring metric variables
2024-02-20 00:01:32,297:INFO:Importing untrained model
2024-02-20 00:01:32,305:INFO:Ridge Classifier Imported successfully
2024-02-20 00:01:32,321:INFO:Starting cross validation
2024-02-20 00:01:32,323:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-02-20 00:01:32,864:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=4.27346e-11): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-02-20 00:01:32,864:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=4.25191e-11): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-02-20 00:01:32,864:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=4.19174e-11): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-02-20 00:01:32,864:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=4.30875e-11): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-02-20 00:01:32,885:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2024-02-20 00:01:32,890:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2024-02-20 00:01:32,894:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2024-02-20 00:01:32,894:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2024-02-20 00:01:32,952:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=4.26702e-11): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-02-20 00:01:32,954:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=4.23533e-11): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-02-20 00:01:32,968:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2024-02-20 00:01:32,971:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2024-02-20 00:01:33,024:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=4.23617e-11): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-02-20 00:01:33,027:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=4.28608e-11): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-02-20 00:01:33,041:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2024-02-20 00:01:33,047:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2024-02-20 00:01:33,050:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=4.30273e-11): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-02-20 00:01:33,059:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=4.28695e-11): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-02-20 00:01:33,070:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2024-02-20 00:01:33,075:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2024-02-20 00:01:33,099:INFO:Calculating mean and std
2024-02-20 00:01:33,102:INFO:Creating metrics dataframe
2024-02-20 00:01:33,108:INFO:Uploading results into container
2024-02-20 00:01:33,110:INFO:Uploading model into container now
2024-02-20 00:01:33,114:INFO:_master_model_container: 6
2024-02-20 00:01:33,114:INFO:_display_container: 2
2024-02-20 00:01:33,114:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=7041, solver='auto',
                tol=0.0001)
2024-02-20 00:01:33,115:INFO:create_model() successfully completed......................................
2024-02-20 00:01:33,299:INFO:SubProcess create_model() end ==================================
2024-02-20 00:01:33,299:INFO:Creating metrics dataframe
2024-02-20 00:01:33,320:INFO:Initializing Random Forest Classifier
2024-02-20 00:01:33,320:INFO:Total runtime is 1.985491156578064 minutes
2024-02-20 00:01:33,326:INFO:SubProcess create_model() called ==================================
2024-02-20 00:01:33,327:INFO:Initializing create_model()
2024-02-20 00:01:33,327:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f263ebc4b50>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f263fcaead0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-20 00:01:33,328:INFO:Checking exceptions
2024-02-20 00:01:33,328:INFO:Importing libraries
2024-02-20 00:01:33,328:INFO:Copying training dataset
2024-02-20 00:01:33,348:INFO:Defining folds
2024-02-20 00:01:33,350:INFO:Declaring metric variables
2024-02-20 00:01:33,359:INFO:Importing untrained model
2024-02-20 00:01:33,373:INFO:Random Forest Classifier Imported successfully
2024-02-20 00:01:33,393:INFO:Starting cross validation
2024-02-20 00:01:33,395:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-02-20 00:01:38,419:INFO:Calculating mean and std
2024-02-20 00:01:38,422:INFO:Creating metrics dataframe
2024-02-20 00:01:38,426:INFO:Uploading results into container
2024-02-20 00:01:38,428:INFO:Uploading model into container now
2024-02-20 00:01:38,429:INFO:_master_model_container: 7
2024-02-20 00:01:38,430:INFO:_display_container: 2
2024-02-20 00:01:38,431:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=7041, verbose=0, warm_start=False)
2024-02-20 00:01:38,431:INFO:create_model() successfully completed......................................
2024-02-20 00:01:38,619:INFO:SubProcess create_model() end ==================================
2024-02-20 00:01:38,619:INFO:Creating metrics dataframe
2024-02-20 00:01:38,635:INFO:Initializing Quadratic Discriminant Analysis
2024-02-20 00:01:38,635:INFO:Total runtime is 2.0740761756896973 minutes
2024-02-20 00:01:38,642:INFO:SubProcess create_model() called ==================================
2024-02-20 00:01:38,643:INFO:Initializing create_model()
2024-02-20 00:01:38,644:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f263ebc4b50>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f263fcaead0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-20 00:01:38,644:INFO:Checking exceptions
2024-02-20 00:01:38,644:INFO:Importing libraries
2024-02-20 00:01:38,644:INFO:Copying training dataset
2024-02-20 00:01:38,665:INFO:Defining folds
2024-02-20 00:01:38,666:INFO:Declaring metric variables
2024-02-20 00:01:38,676:INFO:Importing untrained model
2024-02-20 00:01:38,687:INFO:Quadratic Discriminant Analysis Imported successfully
2024-02-20 00:01:38,703:INFO:Starting cross validation
2024-02-20 00:01:38,706:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-02-20 00:01:40,668:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2024-02-20 00:01:40,668:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2024-02-20 00:01:40,668:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2024-02-20 00:01:40,668:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2024-02-20 00:01:40,781:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2024-02-20 00:01:40,782:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2024-02-20 00:01:40,793:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2024-02-20 00:01:40,823:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2024-02-20 00:01:40,909:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2024-02-20 00:01:40,916:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2024-02-20 00:01:40,963:INFO:Calculating mean and std
2024-02-20 00:01:40,965:INFO:Creating metrics dataframe
2024-02-20 00:01:40,968:INFO:Uploading results into container
2024-02-20 00:01:40,969:INFO:Uploading model into container now
2024-02-20 00:01:40,970:INFO:_master_model_container: 8
2024-02-20 00:01:40,970:INFO:_display_container: 2
2024-02-20 00:01:40,970:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2024-02-20 00:01:40,970:INFO:create_model() successfully completed......................................
2024-02-20 00:01:41,164:INFO:SubProcess create_model() end ==================================
2024-02-20 00:01:41,165:INFO:Creating metrics dataframe
2024-02-20 00:01:41,185:INFO:Initializing Ada Boost Classifier
2024-02-20 00:01:41,186:INFO:Total runtime is 2.116584082444509 minutes
2024-02-20 00:01:41,191:INFO:SubProcess create_model() called ==================================
2024-02-20 00:01:41,192:INFO:Initializing create_model()
2024-02-20 00:01:41,194:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f263ebc4b50>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f263fcaead0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-20 00:01:41,194:INFO:Checking exceptions
2024-02-20 00:01:41,194:INFO:Importing libraries
2024-02-20 00:01:41,194:INFO:Copying training dataset
2024-02-20 00:01:41,215:INFO:Defining folds
2024-02-20 00:01:41,215:INFO:Declaring metric variables
2024-02-20 00:01:41,225:INFO:Importing untrained model
2024-02-20 00:01:41,234:INFO:Ada Boost Classifier Imported successfully
2024-02-20 00:01:41,253:INFO:Starting cross validation
2024-02-20 00:01:41,255:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-02-20 00:01:44,153:INFO:Calculating mean and std
2024-02-20 00:01:44,157:INFO:Creating metrics dataframe
2024-02-20 00:01:44,161:INFO:Uploading results into container
2024-02-20 00:01:44,163:INFO:Uploading model into container now
2024-02-20 00:01:44,166:INFO:_master_model_container: 9
2024-02-20 00:01:44,167:INFO:_display_container: 2
2024-02-20 00:01:44,169:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=7041)
2024-02-20 00:01:44,169:INFO:create_model() successfully completed......................................
2024-02-20 00:01:44,394:INFO:SubProcess create_model() end ==================================
2024-02-20 00:01:44,395:INFO:Creating metrics dataframe
2024-02-20 00:01:44,412:INFO:Initializing Gradient Boosting Classifier
2024-02-20 00:01:44,413:INFO:Total runtime is 2.1703675587972007 minutes
2024-02-20 00:01:44,422:INFO:SubProcess create_model() called ==================================
2024-02-20 00:01:44,423:INFO:Initializing create_model()
2024-02-20 00:01:44,423:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f263ebc4b50>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f263fcaead0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-20 00:01:44,424:INFO:Checking exceptions
2024-02-20 00:01:44,424:INFO:Importing libraries
2024-02-20 00:01:44,424:INFO:Copying training dataset
2024-02-20 00:01:44,450:INFO:Defining folds
2024-02-20 00:01:44,450:INFO:Declaring metric variables
2024-02-20 00:01:44,473:INFO:Importing untrained model
2024-02-20 00:01:44,490:INFO:Gradient Boosting Classifier Imported successfully
2024-02-20 00:01:44,528:INFO:Starting cross validation
2024-02-20 00:01:44,530:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-02-20 00:01:51,489:INFO:Calculating mean and std
2024-02-20 00:01:51,493:INFO:Creating metrics dataframe
2024-02-20 00:01:51,498:INFO:Uploading results into container
2024-02-20 00:01:51,500:INFO:Uploading model into container now
2024-02-20 00:01:51,501:INFO:_master_model_container: 10
2024-02-20 00:01:51,502:INFO:_display_container: 2
2024-02-20 00:01:51,503:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=7041, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2024-02-20 00:01:51,503:INFO:create_model() successfully completed......................................
2024-02-20 00:01:51,738:INFO:SubProcess create_model() end ==================================
2024-02-20 00:01:51,738:INFO:Creating metrics dataframe
2024-02-20 00:01:51,758:INFO:Initializing Linear Discriminant Analysis
2024-02-20 00:01:51,758:INFO:Total runtime is 2.292793134848277 minutes
2024-02-20 00:01:51,767:INFO:SubProcess create_model() called ==================================
2024-02-20 00:01:51,768:INFO:Initializing create_model()
2024-02-20 00:01:51,768:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f263ebc4b50>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f263fcaead0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-20 00:01:51,768:INFO:Checking exceptions
2024-02-20 00:01:51,769:INFO:Importing libraries
2024-02-20 00:01:51,769:INFO:Copying training dataset
2024-02-20 00:01:51,790:INFO:Defining folds
2024-02-20 00:01:51,790:INFO:Declaring metric variables
2024-02-20 00:01:51,799:INFO:Importing untrained model
2024-02-20 00:01:51,814:INFO:Linear Discriminant Analysis Imported successfully
2024-02-20 00:01:51,836:INFO:Starting cross validation
2024-02-20 00:01:51,838:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-02-20 00:01:54,129:INFO:Calculating mean and std
2024-02-20 00:01:54,136:INFO:Creating metrics dataframe
2024-02-20 00:01:54,143:INFO:Uploading results into container
2024-02-20 00:01:54,144:INFO:Uploading model into container now
2024-02-20 00:01:54,146:INFO:_master_model_container: 11
2024-02-20 00:01:54,146:INFO:_display_container: 2
2024-02-20 00:01:54,146:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2024-02-20 00:01:54,146:INFO:create_model() successfully completed......................................
2024-02-20 00:01:54,407:INFO:SubProcess create_model() end ==================================
2024-02-20 00:01:54,407:INFO:Creating metrics dataframe
2024-02-20 00:01:54,437:INFO:Initializing Extra Trees Classifier
2024-02-20 00:01:54,438:INFO:Total runtime is 2.3374500950177515 minutes
2024-02-20 00:01:54,448:INFO:SubProcess create_model() called ==================================
2024-02-20 00:01:54,449:INFO:Initializing create_model()
2024-02-20 00:01:54,449:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f263ebc4b50>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f263fcaead0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-20 00:01:54,449:INFO:Checking exceptions
2024-02-20 00:01:54,449:INFO:Importing libraries
2024-02-20 00:01:54,449:INFO:Copying training dataset
2024-02-20 00:01:54,474:INFO:Defining folds
2024-02-20 00:01:54,475:INFO:Declaring metric variables
2024-02-20 00:01:54,489:INFO:Importing untrained model
2024-02-20 00:01:54,506:INFO:Extra Trees Classifier Imported successfully
2024-02-20 00:01:54,533:INFO:Starting cross validation
2024-02-20 00:01:54,535:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-02-20 00:01:58,454:INFO:Calculating mean and std
2024-02-20 00:01:58,458:INFO:Creating metrics dataframe
2024-02-20 00:01:58,467:INFO:Uploading results into container
2024-02-20 00:01:58,468:INFO:Uploading model into container now
2024-02-20 00:01:58,469:INFO:_master_model_container: 12
2024-02-20 00:01:58,469:INFO:_display_container: 2
2024-02-20 00:01:58,470:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=7041, verbose=0, warm_start=False)
2024-02-20 00:01:58,473:INFO:create_model() successfully completed......................................
2024-02-20 00:01:58,699:INFO:SubProcess create_model() end ==================================
2024-02-20 00:01:58,699:INFO:Creating metrics dataframe
2024-02-20 00:01:58,723:INFO:Initializing Light Gradient Boosting Machine
2024-02-20 00:01:58,723:INFO:Total runtime is 2.4088795383771267 minutes
2024-02-20 00:01:58,732:INFO:SubProcess create_model() called ==================================
2024-02-20 00:01:58,732:INFO:Initializing create_model()
2024-02-20 00:01:58,733:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f263ebc4b50>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f263fcaead0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-20 00:01:58,733:INFO:Checking exceptions
2024-02-20 00:01:58,733:INFO:Importing libraries
2024-02-20 00:01:58,733:INFO:Copying training dataset
2024-02-20 00:01:58,758:INFO:Defining folds
2024-02-20 00:01:58,770:INFO:Declaring metric variables
2024-02-20 00:01:58,778:INFO:Importing untrained model
2024-02-20 00:01:58,791:INFO:Light Gradient Boosting Machine Imported successfully
2024-02-20 00:01:58,833:INFO:Starting cross validation
2024-02-20 00:01:58,835:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-02-20 00:07:34,802:INFO:Calculating mean and std
2024-02-20 00:07:34,805:INFO:Creating metrics dataframe
2024-02-20 00:07:34,810:INFO:Uploading results into container
2024-02-20 00:07:34,811:INFO:Uploading model into container now
2024-02-20 00:07:34,811:INFO:_master_model_container: 13
2024-02-20 00:07:34,812:INFO:_display_container: 2
2024-02-20 00:07:34,813:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=7041, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2024-02-20 00:07:34,814:INFO:create_model() successfully completed......................................
2024-02-20 00:07:35,006:INFO:SubProcess create_model() end ==================================
2024-02-20 00:07:35,006:INFO:Creating metrics dataframe
2024-02-20 00:07:35,028:INFO:Initializing Dummy Classifier
2024-02-20 00:07:35,028:INFO:Total runtime is 8.013960401217144 minutes
2024-02-20 00:07:35,035:INFO:SubProcess create_model() called ==================================
2024-02-20 00:07:35,035:INFO:Initializing create_model()
2024-02-20 00:07:35,036:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f263ebc4b50>, estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f263fcaead0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-20 00:07:35,036:INFO:Checking exceptions
2024-02-20 00:07:35,036:INFO:Importing libraries
2024-02-20 00:07:35,036:INFO:Copying training dataset
2024-02-20 00:07:35,056:INFO:Defining folds
2024-02-20 00:07:35,056:INFO:Declaring metric variables
2024-02-20 00:07:35,066:INFO:Importing untrained model
2024-02-20 00:07:35,074:INFO:Dummy Classifier Imported successfully
2024-02-20 00:07:35,090:INFO:Starting cross validation
2024-02-20 00:07:35,093:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-02-20 00:07:35,402:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2024-02-20 00:07:35,402:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2024-02-20 00:07:35,402:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2024-02-20 00:07:35,407:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2024-02-20 00:07:35,517:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2024-02-20 00:07:35,557:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2024-02-20 00:07:35,560:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2024-02-20 00:07:35,572:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2024-02-20 00:07:35,603:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2024-02-20 00:07:35,654:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2024-02-20 00:07:35,678:INFO:Calculating mean and std
2024-02-20 00:07:35,684:INFO:Creating metrics dataframe
2024-02-20 00:07:35,691:INFO:Uploading results into container
2024-02-20 00:07:35,699:INFO:Uploading model into container now
2024-02-20 00:07:35,702:INFO:_master_model_container: 14
2024-02-20 00:07:35,703:INFO:_display_container: 2
2024-02-20 00:07:35,704:INFO:DummyClassifier(constant=None, random_state=7041, strategy='prior')
2024-02-20 00:07:35,704:INFO:create_model() successfully completed......................................
2024-02-20 00:07:35,924:INFO:SubProcess create_model() end ==================================
2024-02-20 00:07:35,924:INFO:Creating metrics dataframe
2024-02-20 00:07:36,308:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/pycaret/internal/pycaret_experiment/supervised_experiment.py:339: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  .applymap(highlight_cols, subset=["TT (Sec)"])

2024-02-20 00:07:36,329:INFO:Initializing create_model()
2024-02-20 00:07:36,329:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f263ebc4b50>, estimator=RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=7041, solver='auto',
                tol=0.0001), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-20 00:07:36,329:INFO:Checking exceptions
2024-02-20 00:07:36,350:INFO:Importing libraries
2024-02-20 00:07:36,351:INFO:Copying training dataset
2024-02-20 00:07:36,381:INFO:Defining folds
2024-02-20 00:07:36,381:INFO:Declaring metric variables
2024-02-20 00:07:36,382:INFO:Importing untrained model
2024-02-20 00:07:36,382:INFO:Declaring custom model
2024-02-20 00:07:36,383:INFO:Ridge Classifier Imported successfully
2024-02-20 00:07:36,385:INFO:Cross validation set to False
2024-02-20 00:07:36,385:INFO:Fitting Model
2024-02-20 00:07:36,458:WARNING:/home/sensei/Repos/EDA-Analysis/EDA_venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=3.83382e-11): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-02-20 00:07:36,459:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=7041, solver='auto',
                tol=0.0001)
2024-02-20 00:07:36,459:INFO:create_model() successfully completed......................................
2024-02-20 00:07:37,256:INFO:_master_model_container: 14
2024-02-20 00:07:37,257:INFO:_display_container: 2
2024-02-20 00:07:37,258:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=7041, solver='auto',
                tol=0.0001)
2024-02-20 00:07:37,258:INFO:compare_models() successfully completed......................................
2024-02-20 00:19:39,998:INFO:Initializing predict_model()
2024-02-20 00:19:40,149:INFO:predict_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f263ebc4b50>, estimator=RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=7041, solver='auto',
                tol=0.0001), probability_threshold=None, encoded_labels=False, raw_score=False, round=4, verbose=True, ml_usecase=None, preprocess=True, encode_labels=<function _SupervisedExperiment.predict_model.<locals>.encode_labels at 0x7f263e718040>)
2024-02-20 00:19:40,163:INFO:Checking exceptions
2024-02-20 00:19:40,163:INFO:Preloading libraries
2024-02-20 00:19:40,167:INFO:Set up data.
2024-02-20 00:19:40,237:INFO:Set up index.
2024-02-20 00:25:35,103:INFO:Initializing predict_model()
2024-02-20 00:25:35,105:INFO:predict_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f263ebc4b50>, estimator=RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=7041, solver='auto',
                tol=0.0001), probability_threshold=None, encoded_labels=False, raw_score=False, round=4, verbose=True, ml_usecase=None, preprocess=True, encode_labels=<function _SupervisedExperiment.predict_model.<locals>.encode_labels at 0x7f263e71bce0>)
2024-02-20 00:25:35,105:INFO:Checking exceptions
2024-02-20 00:25:35,105:INFO:Preloading libraries
2024-02-20 00:25:35,115:INFO:Set up data.
2024-02-20 00:25:35,131:INFO:Set up index.
2024-02-20 00:26:39,090:INFO:Initializing save_model()
2024-02-20 00:26:39,091:INFO:save_model(model=RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=7041, solver='auto',
                tol=0.0001), model_name=ridge, prep_pipe_=Pipeline(memory=FastMemory(location=/tmp/joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['tenure', 'MonthlyCharges',
                                             'TotalCharges',
                                             'MonthlyCharges_log',
                                             'TotalCharges_Tenure_Ratio',
                                             'MonthlyCharges_to_TotalCharges_Ratio',
                                             'Bank transfer (automatic)',
                                             'Credit card (automatic)',
                                             'Electronic check', 'Mailed check',
                                             'Month-to-month', 'One...
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated'))),
                ('clean_column_names',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+')))],
         verbose=False), verbose=True, use_case=MLUsecase.CLASSIFICATION, kwargs={})
2024-02-20 00:26:39,091:INFO:Adding model into prep_pipe
2024-02-20 00:26:39,099:INFO:ridge.pkl saved in current working directory
2024-02-20 00:26:39,113:INFO:Pipeline(memory=Memory(location=None),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['tenure', 'MonthlyCharges',
                                             'TotalCharges',
                                             'MonthlyCharges_log',
                                             'TotalCharges_Tenure_Ratio',
                                             'MonthlyCharges_to_TotalCharges_Ratio',
                                             'Bank transfer (automatic)',
                                             'Credit card (automatic)',
                                             'Electronic check', 'Mailed check',
                                             'Month-to-month', 'One year',
                                             'Two y...
                                                              strategy='most_frequent',
                                                              verbose='deprecated'))),
                ('clean_column_names',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+'))),
                ('trained_model',
                 RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True,
                                 fit_intercept=True, max_iter=None,
                                 positive=False, random_state=7041,
                                 solver='auto', tol=0.0001))],
         verbose=False)
2024-02-20 00:26:39,113:INFO:save_model() successfully completed......................................
2024-02-20 00:30:58,473:INFO:Initializing load_model()
2024-02-20 00:30:58,478:INFO:load_model(model_name=ridge, platform=None, authentication=None, verbose=True)
2024-02-20 00:30:59,374:INFO:Initializing predict_model()
2024-02-20 00:30:59,374:INFO:predict_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f263ebc4b50>, estimator=Pipeline(memory=FastMemory(location=/tmp/joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['tenure', 'MonthlyCharges',
                                             'TotalCharges',
                                             'MonthlyCharges_log',
                                             'TotalCharges_Tenure_Ratio',
                                             'MonthlyCharges_to_TotalCharges_Ratio',
                                             'Bank transfer (automatic)',
                                             'Credit card (automatic)',
                                             'Electronic check', 'Mailed check',
                                             'Month-to-month', 'One...
                                                              strategy='most_frequent',
                                                              verbose='deprecated'))),
                ('clean_column_names',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+'))),
                ('trained_model',
                 RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True,
                                 fit_intercept=True, max_iter=None,
                                 positive=False, random_state=7041,
                                 solver='auto', tol=0.0001))],
         verbose=False), probability_threshold=None, encoded_labels=False, raw_score=False, round=4, verbose=True, ml_usecase=None, preprocess=True, encode_labels=<function _SupervisedExperiment.predict_model.<locals>.encode_labels at 0x7f263e718e00>)
2024-02-20 00:30:59,374:INFO:Checking exceptions
2024-02-20 00:30:59,374:INFO:Preloading libraries
2024-02-20 00:30:59,378:INFO:Set up data.
2024-02-20 00:30:59,390:INFO:Set up index.
2024-02-20 00:32:20,988:INFO:Initializing load_model()
2024-02-20 00:32:20,989:INFO:load_model(model_name=ridge, platform=None, authentication=None, verbose=True)
2024-02-20 00:32:21,008:INFO:Initializing predict_model()
2024-02-20 00:32:21,009:INFO:predict_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f263ebc4b50>, estimator=Pipeline(memory=FastMemory(location=/tmp/joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['tenure', 'MonthlyCharges',
                                             'TotalCharges',
                                             'MonthlyCharges_log',
                                             'TotalCharges_Tenure_Ratio',
                                             'MonthlyCharges_to_TotalCharges_Ratio',
                                             'Bank transfer (automatic)',
                                             'Credit card (automatic)',
                                             'Electronic check', 'Mailed check',
                                             'Month-to-month', 'One...
                                                              strategy='most_frequent',
                                                              verbose='deprecated'))),
                ('clean_column_names',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+'))),
                ('trained_model',
                 RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True,
                                 fit_intercept=True, max_iter=None,
                                 positive=False, random_state=7041,
                                 solver='auto', tol=0.0001))],
         verbose=False), probability_threshold=None, encoded_labels=False, raw_score=False, round=4, verbose=True, ml_usecase=None, preprocess=True, encode_labels=<function _SupervisedExperiment.predict_model.<locals>.encode_labels at 0x7f263e71bba0>)
2024-02-20 00:32:21,009:INFO:Checking exceptions
2024-02-20 00:32:21,009:INFO:Preloading libraries
2024-02-20 00:32:21,014:INFO:Set up data.
2024-02-20 00:32:21,022:INFO:Set up index.
2024-02-20 00:32:21,321:WARNING:/home/sensei/Repos/EDA-Analysis/Week5/F/predict_churn.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  predictions['Churn_prediction'].replace({1: 'Churn', 0: 'No Churn'}, inplace=True)

